/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
#define ADC_BASE_ADDR	0X40012000UL
#define ADC_CR1_REG_OFFSET	0X04UL
#define ADC_CR1_REG_ADDR	(ADC_BASE_ADDR + ADC_CR1_REG_OFFSET)

#define RCC_BASE_ADDR	0X40023800UL
#define RCC_APB2ENR_REG_OFFSET	0X44UL
#define RCC_APB2ENR_REG_ADDR	(RCC_BASE_ADDR + RCC_APB2ENR_REG_OFFSET)

#define SPI_BASE_ADDR	0x40013000UL
#define SPI_CR1_REG_OFFSET	0x00UL
#define SPI_CR1_REG_ADDR	(SPI_BASE_ADDR + SPI_CR1_REG_OFFSET)

int main(void)
{
	uint32_t *pAddcCr1Reg = (uint32_t*)ADC_CR1_REG_ADDR;
	uint32_t *pRCCAPb2ENrReg = (uint32_t*)RCC_APB2ENR_REG_ADDR;
	uint32_t *pSPIcCr1Reg = (uint32_t*)SPI_CR1_REG_ADDR;

	*pRCCAPb2ENrReg |=(1<<12);
	*pAddcCr1Reg |=(1<<8);
	*pSPIcCr1Reg |=(1<<6);


    /* Loop forever */
	for(;;);
}
